"""Self-contained offline HTML browser for genome_coherence diagnostic output."""
from __future__ import annotations

import json
from pathlib import Path


def write_browser(path, data):
    # Escape '<' to prevent an identifier containing </script> ending the JSON tag.
    encoded = json.dumps(data, separators=(",", ":"), allow_nan=False).replace("<", "\\u003c")
    encoded = encoded.replace("\u2028", "\\u2028").replace("\u2029", "\\u2029")
    Path(path).write_text(TEMPLATE.replace("__EVIDENCE_JSON__", encoded), encoding="utf-8")


TEMPLATE = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>GOTTCHA2 | Coordinate-aware evidence</title>
<style>
:root{--ink:#142c43;--muted:#5e7080;--line:#dce5ec;--bg:#f2f6f9;--all:#357eb1;--exclusive:#138c7b;--residual:#985ba7;--sig:#c7d0d8;--amber:#976020}
*{box-sizing:border-box}body{margin:0;background:var(--bg);font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:var(--ink);font-size:14px}
header{padding:28px 38px;background:#122c43;color:white}header small{font-size:11px;letter-spacing:2px;color:#91c1de}h1{font-size:27px;font-weight:650;margin:7px 0}header p{margin:6px 0;color:#c4d6e3;max-width:1100px;line-height:1.5}
main{max-width:1600px;margin:auto;padding:24px 32px 45px}.banner{border-left:4px solid #cc9b44;background:#fff8e8;padding:13px 17px;line-height:1.5;margin-bottom:20px}
.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.metric{background:white;border:1px solid var(--line);border-radius:8px;padding:17px}.metric b{display:block;font-size:26px}.metric span{color:var(--muted);font-size:12px}
section{background:white;border:1px solid var(--line);border-radius:9px;margin:17px 0;padding:20px}h2{font-size:18px;margin:0 0 6px}h3{font-size:15px}.note{color:var(--muted);font-size:12px;line-height:1.5;margin:4px 0 13px}.controls{display:flex;flex-wrap:wrap;gap:12px;margin:15px 0;align-items:end}.controls label{font-size:11px;font-weight:650;letter-spacing:.3px;display:grid;gap:5px;color:var(--muted)}
select,input,button{padding:9px 11px;border:1px solid #c8d5df;border-radius:5px;background:white;color:var(--ink);font:inherit}select{max-width:560px}input[type=search]{min-width:260px}button{cursor:pointer}.legend{display:flex;gap:18px;flex-wrap:wrap;font-size:12px;color:var(--muted);margin:12px 0}.swatch{display:inline-block;width:13px;height:8px;margin-right:6px;vertical-align:middle}.track{border-top:1px solid var(--line);padding:15px 0 4px}.track h3{margin:0 0 2px}.track svg{width:100%;height:auto;display:block;min-width:600px}.scroll{overflow:auto}.empty{padding:30px;color:var(--muted);text-align:center}
table{border-collapse:collapse;width:100%;font-size:12px;white-space:nowrap}th{text-align:left;background:#edf3f7;color:#365267;cursor:pointer;position:sticky;top:0;padding:10px 11px}td{border-bottom:1px solid #e8eef3;padding:9px 11px}tr.clickable{cursor:pointer}tr.clickable:hover{background:#edf6fa}.tablebox{max-height:340px;overflow:auto;border:1px solid var(--line);border-radius:5px}.badge{font-size:10px;background:#e9eff4;padding:3px 6px;border-radius:4px;display:inline-block}.subgrid{display:grid;grid-template-columns:1fr 1fr;gap:16px}#moleculeView{border-top:1px solid var(--line);padding-top:10px;margin-top:15px}#moleculeView svg{width:100%;max-height:270px}.warnings{line-height:1.65;font-size:12px;color:var(--muted)}details summary{cursor:pointer}#selectionMeta{font-size:12px;color:var(--muted);line-height:1.6}.foot{font-size:11px;color:var(--muted);margin-top:16px}.pill{background:#e7f3ef;color:#196f59;padding:3px 7px;border-radius:4px}.small{font-size:11px;color:var(--muted)}
@media(max-width:800px){main{padding:15px}header{padding:22px}.metrics{grid-template-columns:1fr 1fr}.subgrid{grid-template-columns:1fr}select{max-width:340px}}
</style></head><body>
<header><small>GOTTCHA2 / EXPERIMENTAL DIAGNOSTICS</small><h1>Coordinate-aware mapping evidence</h1><p>Reference-anchored signature coverage and physical molecule links. Assemblies remain separate; these tracks are not a reconstructed genome.</p></header>
<main>
<div class="banner"><strong>Evidence, not species calls.</strong> A connected component can contain multiple real organisms. Query-exclusive support is relative to the retained alignments, not proof of species-specific sequence. No profiles or abundances were changed.</div>
<div class="metrics" id="metrics"></div>
<section><h2>Native genomic coordinates</h2><p class="note">Gray intervals show all eligible signatures, including zero-coverage regions. Thin strips show exact aligned-base intervals; depth bars are windowed. Support tracks use the same vertical scale. Missing contig lengths are explicitly shown as signature-bounded extents.</p>
<div class="controls"><label>FILTER ASSEMBLIES<input type="search" id="search" placeholder="Species name, taxid, or assembly"></label><label>ASSEMBLY<select id="assembly"></select></label><label>CONTIG<select id="contig"></select></label><label>WINDOW SIZE<select id="width"></select></label><label>DISPLAY<select id="measure"><option value="mean_signature_depth">Signature depth</option><option value="molecules">Molecules per window</option><option value="breadth">Signature breadth</option></select></label></div>
<div id="selectionMeta"></div><div class="legend"><span><i class="swatch" style="background:var(--sig)"></i>Eligible signature</span><span><i class="swatch" style="background:var(--all)"></i>All-compatible support</span><span><i class="swatch" style="background:var(--exclusive)"></i>Query-exclusive support</span><span id="residualLegend"><i class="swatch" style="background:var(--residual)"></i>Conditional residual</span></div>
<div id="tracks" class="scroll"></div></section>
<section><h2>Species support and candidate components</h2><p class="note">Click a row to inspect an assembly. Molecules are deduplicated within each species; counts need not sum to the sample total. Species are not collapsed to a single winner.</p><div id="speciesTable" class="tablebox"></div></section>
<section><h2>Cross-species relationship graph</h2><p class="note">The graph shows the selected candidate component. Solid edges have physical split-read or paired-end support; dashed edges have alternative placements only. Edge labels are unique molecules, not alignment counts.</p><div id="graph"></div><div id="edgeTable" class="tablebox"></div></section>
<section><h2>Molecule-level links</h2><p class="note" id="linkNote"></p><div class="controls"><label>LINK TYPE<select id="linkKind"><option value="all">All links</option><option value="alternative">Alternative mappings</option><option value="split">Split-read links</option><option value="pair">Paired-end links</option></select></label><label>GEOMETRY<select id="linkStatus"><option value="all">All statuses</option><option>concordant</option><option>discordant</option><option>orientation_only</option><option>not_evaluable</option><option>not_applicable</option></select></label></div><div id="linkTable" class="tablebox"></div><div id="moleculeView"><p class="note">Select a link to inspect the corresponding query segments and reference intervals.</p></div></section>
<section><details><summary><strong>Provenance and interpretation limits</strong></summary><div id="warnings" class="warnings"></div><pre id="provenance" style="white-space:pre-wrap;font-size:11px"></pre></details></section>
<p class="foot">Coordinates are 0-based, half-open in exported tables. Full links and exact union-coverage intervals are retained in the compressed TSV outputs. This file is self-contained and requires no network connection.</p>
</main><script id="evidence-data" type="application/json">__EVIDENCE_JSON__</script><script>
'use strict';
const D=JSON.parse(document.getElementById('evidence-data').textContent), $=id=>document.getElementById(id);
const fmt=x=>x===null||x===undefined?'NA':typeof x==='number'?(Number.isInteger(x)?x.toLocaleString():x.toPrecision(4)):String(x);
const colors={all:'#357eb1',query_exclusive:'#138c7b',conditional_residual:'#985ba7'};
const labels={all:'All-compatible',query_exclusive:'Query-exclusive',conditional_residual:'Conditional residual'};
const layers=['all','query_exclusive'].concat(D.metadata.config.explainers.length?['conditional_residual']:[]);
const NS='http://www.w3.org/2000/svg';let selectedMolecule=null;
function el(tag,attrs={},text=null){let node=document.createElementNS(NS,tag);for(let [k,v]of Object.entries(attrs))node.setAttribute(k,v);if(text!==null)node.textContent=text;return node;}
function text(x,y,str,attrs={}){return el('text',{x,y,'font-size':11,fill:'#5e7080',...attrs},str)}
function option(value,label){let o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function table(id,rows,columns,click){const host=$(id);host.replaceChildren();if(!rows.length){let p=document.createElement('p');p.className='empty';p.textContent='No matching evidence.';host.append(p);return;}
let sortKey=null,asc=true;function draw(){host.replaceChildren();let t=document.createElement('table'),head=document.createElement('thead'),tr=document.createElement('tr');for(let [key,label] of columns){let th=document.createElement('th');th.textContent=label+(sortKey===key?(asc?' \u2191':' \u2193'):'');th.onclick=()=>{asc=sortKey===key?!asc:true;sortKey=key;rows.sort((a,b)=>{let x=a[key],y=b[key];return (typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??'')))*(asc?1:-1)});draw()};tr.append(th)}head.append(tr);t.append(head);let body=document.createElement('tbody');for(let row of rows){let tr=document.createElement('tr');if(click){tr.className='clickable';tr.onclick=()=>click(row)}for(let [key]of columns){let td=document.createElement('td');td.textContent=fmt(row[key]);tr.append(td)}body.append(tr)}t.append(body);host.append(t)}draw();}
for(let [n,label]of [[D.metadata.counters.eligible_molecules||0,'Eligible physical molecules'],[D.species.length,'Candidate species'],[new Set(D.assemblies.map(x=>x.assembly_id)).size,'Supported reference assemblies'],[Object.keys(D.groups).length,'Candidate components']]){let div=document.createElement('div');div.className='metric';let b=document.createElement('b');b.textContent=fmt(n);let s=document.createElement('span');s.textContent=label;div.append(b,s);$('metrics').append(div)}
$('residualLegend').hidden=!D.metadata.config.explainers.length;
for(let w of D.metadata.config.window_sizes)$('width').append(option(w,fmt(w)+' bp'));
for(let message of D.metadata.warnings){let p=document.createElement('p');p.textContent=message;$('warnings').append(p)}
$('provenance').textContent=JSON.stringify({module_version:D.metadata.module_version,manifest_sha256:D.metadata.manifest_sha256,config:D.metadata.config,counters:D.metadata.counters},null,2);
function updateAssemblies(prefer){let query=$('search').value.toLowerCase(),old=prefer||$('assembly').value;let items=D.assemblies.filter(x=>x.layer==='all'&&x.window_size===D.metadata.config.window_sizes[0]).filter(x=>[x.assembly_id,x.species_taxid,x.species_name].join(' ').toLowerCase().includes(query));items.sort((a,b)=>b.molecules-a.molecules||a.assembly_id.localeCompare(b.assembly_id));$('assembly').replaceChildren();for(let a of items)$('assembly').append(option(a.assembly_id,`${a.species_name||a.species_taxid} | ${a.assembly_id}`));if(items.some(x=>x.assembly_id===old))$('assembly').value=old;updateContigs();}
function updateContigs(){let old=$('contig').value,tracks=D.tracks.filter(t=>t.assembly_id===$('assembly').value);$('contig').replaceChildren(option('all','All signature-bearing contigs'));tracks.sort((a,b)=>b.display_extent-a.display_extent);for(let t of tracks)$('contig').append(option(t.contig_id,t.contig_id));if(tracks.some(x=>x.contig_id===old))$('contig').value=old;render();}
function render(){let assembly=$('assembly').value,width=Number($('width').value),measure=$('measure').value,host=$('tracks');host.replaceChildren();let summary=D.assemblies.find(x=>x.assembly_id===assembly&&x.layer==='all'&&x.window_size===width);if(!summary){host.textContent='No supported assemblies match the selection.';$('selectionMeta').textContent='';renderGraph(null);renderLinks();return;}
$('selectionMeta').textContent=`${fmt(summary.molecules)} molecules | ${fmt(summary.covered_bp)} / ${fmt(summary.signature_bp)} signature bases covered (${(100*summary.signature_breadth).toFixed(2)}%) | ${fmt(summary.occupied_windows)} / ${fmt(summary.callable_windows)} eligible windows supported | Expected occupancy: ${fmt(summary.expected_occupied_windows)} | ${summary.evidence_level}`;
let tracks=D.tracks.filter(t=>t.assembly_id===assembly&&($('contig').value==='all'||t.contig_id===$('contig').value)).sort((a,b)=>b.display_extent-a.display_extent);if(tracks.length>50){let p=document.createElement('p');p.className='note';p.textContent=`Showing 50 of ${tracks.length} contigs. Select a contig to inspect it; exported tables are complete.`;host.append(p);tracks=tracks.slice(0,50)}
for(let track of tracks){let div=document.createElement('div');div.className='track';let h=document.createElement('h3');h.textContent=track.contig_id;let p=document.createElement('p');p.className='note';p.textContent=`${fmt(track.display_extent)} bp ${track.extent_is_signature_bound?'signature-bounded extent (NOT a known contig length)':'reference contig length'} | ${track.topology}`;if(track.coverage_preview_truncated&&track.coverage_preview_truncated.length)p.textContent+=' | Exact interval strip truncated to 5,000 intervals per layer; TSV output is complete.';div.append(h,p);const W=1200,L=155,R=25,pw=W-L-R,extent=track.display_extent,H=65+layers.length*70,x=pos=>L+pw*pos/extent;let svg=el('svg',{viewBox:`0 0 ${W} ${H}`,'aria-label':`Native-coordinate support for ${track.contig_id}`});svg.append(text(0,25,'Eligible signatures'));for(let [a,b]of track.signatures){let rect=el('rect',{x:x(a),y:14,width:Math.max(.7,x(b)-x(a)),height:13,fill:'#c7d0d8'});rect.append(el('title',{},`Signature interval [${a}, ${b})`));svg.append(rect)}
let rows=D.windows.filter(r=>r.assembly_id===assembly&&r.contig_id===track.contig_id&&r.window_size===width);let maximum=rows.reduce((m,r)=>Math.max(m,r[measure]||0),1e-10);if(measure==='breadth')maximum=1;
layers.forEach((layer,i)=>{let y=54+i*70,base=y+43;svg.append(text(0,y+15,labels[layer],{fill:colors[layer]}));svg.append(text(0,y+31,`max ${fmt(maximum)}`,{'font-size':10}));svg.append(el('line',{x1:L,x2:W-R,y1:base,y2:base,stroke:'#dce5ec'}));for(let r of rows.filter(v=>v.layer===layer)){let val=r[measure]||0,height=val/maximum*40;let rect=el('rect',{x:x(r.start0),y:base-height,width:Math.max(.7,x(Math.min(r.end0,extent))-x(r.start0)-.6),height:height,fill:colors[layer]});rect.append(el('title',{},`[${r.start0}, ${r.end0})\n${r.molecules} molecules\n${r.covered_bp}/${r.signature_bp} signature bases covered\nDepth ${fmt(r.mean_signature_depth)}`));svg.append(rect)}for(let [a,b]of (track.coverage?.[layer]||[])){let strip=el('rect',{x:x(a),y:base+3,width:Math.max(.7,x(b)-x(a)),height:3,fill:colors[layer]});strip.append(el('title',{},`Exact covered interval [${a}, ${b})`));svg.append(strip)}});
if(selectedMolecule){for(let link of D.links.filter(l=>l.molecule_id===selectedMolecule&&l.kind!=='alternative'&&l.assembly_a===assembly&&l.assembly_b===assembly&&l.contig_a===track.contig_id&&l.contig_b===track.contig_id)){let xa=x((link.start_a+link.end_a)/2),xb=x((link.start_b+link.end_b)/2);let arc=el('path',{d:`M ${xa} 39 Q ${(xa+xb)/2} 0 ${xb} 39`,stroke:'#b06b1d','stroke-width':2,fill:'none'});arc.append(el('title',{},`${link.kind}: ${link.status}`));svg.append(arc)}}
for(let i=0;i<=5;i++){let pos=Math.round(extent*i/5);svg.append(text(x(pos),H-4,fmt(pos),{'text-anchor':i===0?'start':i===5?'end':'middle','font-size':10}))}div.append(svg);host.append(div)}renderGraph(summary.species_taxid);renderLinks();}
function renderGraph(species){let group=species?D.species.find(x=>x.species_taxid===species)?.component:null;let members=D.groups[group]||[];let rows=D.edges.filter(e=>members.includes(e.species_a)||members.includes(e.species_b));table('edgeTable',rows.slice(),[['species_a','Species A'],['species_b','Species B'],['any_molecules','Linked molecules'],['alternative_molecules','Alternative'],['split_molecules','Split'],['pair_molecules','Paired'],['a_molecules','All A molecules'],['b_molecules','All B molecules'],['a_link_fraction','Fraction of A'],['b_link_fraction','Fraction of B'],['kept','Grouping edge']]);let host=$('graph');host.replaceChildren();if(members.length>50){host.textContent='Component too large for the compact graph; inspect the complete edge table.';return;}if(!members.length)return;let svg=el('svg',{viewBox:'0 0 1100 240',style:'width:100%;max-height:240px'}),pos={};members.forEach((sp,i)=>{let theta=2*Math.PI*i/Math.max(1,members.length);pos[sp]=members.length===1?[550,120]:[550+380*Math.cos(theta),120+78*Math.sin(theta)]});for(let e of rows.filter(e=>e.kept&&pos[e.species_a]&&pos[e.species_b])){let [x1,y1]=pos[e.species_a],[x2,y2]=pos[e.species_b];svg.append(el('line',{x1,y1,x2,y2,stroke:'#9aadb9','stroke-width':Math.min(7,1+Math.log2(e.any_molecules+1)),'stroke-dasharray':e.split_molecules+e.pair_molecules?'none':'5,5'}));svg.append(text((x1+x2)/2,(y1+y2)/2-6,fmt(e.any_molecules),{'text-anchor':'middle',fill:'#536d7f'}))}for(let sp of members){let [x,y]=pos[sp],s=D.species.find(v=>v.species_taxid===sp),g=el('g',{style:'cursor:pointer'});g.append(el('circle',{cx:x,cy:y,r:9,fill:sp===species?'#138c7b':'#357eb1'}));g.append(text(x,y+24,(s.species_name||sp).slice(0,52),{'text-anchor':'middle',fill:'#142c43'}));g.onclick=()=>{$('search').value='';updateAssemblies(s.assembly_ids.split(';')[0])};svg.append(g)}host.append(svg)}
function renderLinks(){let assembly=$('assembly').value,kind=$('linkKind').value,status=$('linkStatus').value;let rows=D.links.filter(x=>(x.assembly_a===assembly||x.assembly_b===assembly)&&(kind==='all'||x.kind===kind)&&(status==='all'||x.status===status));$('linkNote').textContent=`${fmt(rows.length)} matching links in the HTML preview (${fmt(D.metadata.browser_link_count)} of ${fmt(D.metadata.counters.link_records||0)} total link records embedded). ${D.metadata.browser_links_truncated?'Preview is truncated in deterministic molecule order; use links.tsv.gz for complete evidence.':'All link records are embedded.'} Cross-assembly geometry is not evaluated.`;table('linkTable',rows.slice(),[['molecule_id','Molecule'],['kind','Type'],['species_a','Species A'],['contig_a','Contig A'],['start_a','Start A'],['species_b','Species B'],['contig_b','Contig B'],['start_b','Start B'],['status','Geometry'],['reason','Reason'],['gap_error','Gap error'],['insert_size','Fragment span']],row=>{selectedMolecule=row.molecule_id;renderMolecule(row.molecule_id);render()})}
function renderMolecule(id){let host=$('moleculeView');host.replaceChildren();let h=document.createElement('h3');h.textContent='Molecule '+id;host.append(h);let p=document.createElement('p');p.className='note';p.textContent='Original-query coordinates for the displayed alignment segments. Each read end has its own axis; different references are not stitched into a genome. Only segments represented by embedded links are shown.';host.append(p);let segments=new Map();for(let l of D.links.filter(x=>x.molecule_id===id)){for(let k of ['a','b']){let s={end:l['read_end_'+k],start:l['query_start_'+k],stop:l['query_end_'+k],species:l['species_'+k],assembly:l['assembly_'+k],contig:l['contig_'+k],rstart:l['start_'+k],rend:l['end_'+k],strand:l['strand_'+k]};segments.set(JSON.stringify(s),s)}}let all=[...segments.values()],ends=[...new Set(all.map(s=>s.end))].sort(),svg=el('svg',{viewBox:`0 0 1200 ${55+ends.length*85}`});ends.forEach((end,i)=>{let vals=all.filter(s=>s.end===end).sort((a,b)=>a.start-b.start||a.species.localeCompare(b.species)),max=Math.max(...vals.map(s=>s.stop),1),x=v=>155+1010*v/max,y=30+i*85;svg.append(text(0,y+12,end===0?'Long / unpaired read':'Read end '+end));svg.append(el('line',{x1:155,x2:1165,y1:y+16,y2:y+16,stroke:'#c7d0d8'}));vals.forEach((s,j)=>{let yy=y+(j%2)*22;let r=el('rect',{x:x(s.start),y:yy,width:Math.max(1,x(s.stop)-x(s.start)),height:15,fill:j%2?'#138c7b':'#357eb1',opacity:.85});r.append(el('title',{},`Species ${s.species}\nQuery [${s.start},${s.stop})\n${s.assembly} / ${s.contig} [${s.rstart},${s.rend}) ${s.strand}`));svg.append(r)});svg.append(text(155,y+61,'0'));svg.append(text(1165,y+61,fmt(max),{'text-anchor':'end'}))});host.append(svg)}
table('speciesTable',D.species.slice(),[['species_name','Species'],['species_taxid','Taxid'],['component','Component'],['molecules','All-compatible molecules'],['query_exclusive_molecules','Query-exclusive molecules'],['conditional_residual_molecules','Conditional residual molecules'],['assemblies_with_support','Assemblies'],['source_status','Source status']],row=>{$('search').value='';updateAssemblies(row.assembly_ids.split(';')[0])});
$('search').oninput=()=>updateAssemblies();$('assembly').onchange=()=>{selectedMolecule=null;updateContigs()};$('contig').onchange=render;$('width').onchange=render;$('measure').onchange=render;$('linkKind').onchange=renderLinks;$('linkStatus').onchange=renderLinks;updateAssemblies();
</script></body></html>'''
